### ISSUE TITLE
Preselected items not selected in DropDown

### ISSUE THREAD

**Issue by mattem86** [sdl/Multiselect-ComboBox#12]
I bind the SelectedItems property to an ObservableCollection, which is prefilled as soon the data object is loaded. It works partly, because they appear in the SelectedItems TextBlock, but they are not selected in the dropdown listbox. I can click the items of the listbox, they would be added to the selecteditems, but I can't get rid of the preselected (or programmatically selected) items. I tried it with system types like ints, but nothing changed.

Please see the attached screenshot, maybe its clearer then.
![2](https://user-images.githubusercontent.com/421110/60247986-ffd88200-98c1-11e9-98d9-633008a0d5ad.PNG)
![1](https://user-images.githubusercontent.com/421110/60247987-00711880-98c2-11e9-94b3-a86fdf035ba8.PNG)

**Comment by Impertatore** [comment]
Hi @mattem86,

Can you please provide some info on the viewModel and how it is associated with the view, as it is most likely associated with binding; also with reference to your code example [here](https://github.com/sdl/Multiselect-ComboBox/issues/11).

If you prefer, please send your code example/project to me at phartnett@sdl.com so that I can take a peek and respond better.

**Comment by mattem86** [comment]
Hi, sorry for the late reply, I was on vacation and not able to work on this. Today I got it, I thought C# would be clever enough, but it makes apparently a different from which collection I preselect my items. Now i search the specific ids from my itemsource and copy them to my selecteditem storage. Voila, case closed :)
